### ISSUE TITLE
Questions about JOSS paper

### ISSUE THREAD

**Issue by danielruss** [occupationMeasurement/occupationMeasurement#6]
I am trying to recreate figure 1.   I followed the instructions in the one of the [vignettes --building your own](https://cran.r-project.org/web/packages/occupationMeasurement/vignettes/app-questionnaire.html#questionnaires) but I get an error:  **Error: multi-argument returns are not permitted.**  

I was able to get your second example to work, and the "getting started" vignette seemed to work.  

Is any project using occupationMeasurement?
~~How do users store the results?~~ Found the answer in the vignette.

The first two sentences of the paper are a little awkward. Consider changing it from a passive sentence, "There is ...", to a more active sentence "People earn a living..."  I would also drop the "easy-to-use" before "R-package" and "easily" before 
"adapt".  The code is easy after going through the learning curve.   

Since your paper does not give examples, I think referencing your vignettes would improve understanding where to get started.  

I was unable to test the docker image (no access to docker).

Otherwise, I think the code addresses a significant problem, and with a few minor corrections should be ready for publication.
(https://github.com/openjournals/joss-reviews/issues/5505)

**Comment by jansim** [comment]
Hi Daniel,
Thanks for your review and the great feedback! Sorry for the delay in my response, somehow I did not receive a notification of this issue.

I agree with the points you raised and adressed them as follows:

> I am trying to recreate figure 1. I followed the instructions in the one of the [vignettes --building your own](https://cran.r-project.org/web/packages/occupationMeasurement/vignettes/app-questionnaire.html#questionnaires) but I get an error: Error: multi-argument returns are not permitted.

Good catch, there was a missing `list()` wrap there. I've updated the vignette to fix this error. ✅

> Is any project using occupationMeasurement?

We were working with a survey institute, who successfully used the API implementation in one of their surveys and also informed some of the API design. Do you think we should mention this somewhere?

Regarding your feedback of the paper itself, I agree with your points and updated the paper to reflect your suggestions. I very much appreciate the helpful feedback!

All the best,
Jan

**Comment by danielruss** [comment]
> We were working with a survey institute, who successfully used the API implementation in one of their surveys and also informed some of the API design. Do you think we should mention this somewhere?

Yes, I think you should mention it towards the end of the paper.  This lets people know that the code is good enough for use in a major study.

**Comment by jansim** [comment]
Great, thanks @danielruss ! I went ahead and also added a line to highlight this.

**Comment by jansim** [comment]
Will go ahead and close this issue, if you have additional comments / wish for some changes feel free to re-open this issue @danielruss. Thank you again for the great comments!
